# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2411920e74489340d37d70633f5274e151ae56709dd7ed90ce3afe9b2aa8e77aae2e03fe19652397bf6b748ae8c660969016e0c9ff7934217ea631dfec75d23

test:
  secret_key_base: ac65a02079b8443c57d141e2cf594eaa8311efba2d0ef04a7816e3663294b94e63c7881009c99dc03ed32c5b7d1f124aa168d92d1863ee1c2d902ab7df207391

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
